apiVersion: v1
kind: Service
metadata:
  name: front-end-service
spec:
  selector:
    app: front-end
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
